// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employees.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees(position, role, years_of_experience, certifications, portfolio_url,created_at,updated_at )
VALUES(
  $1,
  $2,
  $3,
  $4,
  $5,
  NOW(),
  NOW()
)
RETURNING id, position, role, years_of_experience, certifications, portfolio_url, created_at, updated_at
`

type CreateEmployeeParams struct {
	Position          string
	Role              string
	YearsOfExperience string
	Certifications    []string
	PortfolioUrl      sql.NullString
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, createEmployee,
		arg.Position,
		arg.Role,
		arg.YearsOfExperience,
		pq.Array(arg.Certifications),
		arg.PortfolioUrl,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Role,
		&i.YearsOfExperience,
		pq.Array(&i.Certifications),
		&i.PortfolioUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, position, role, years_of_experience, certifications, portfolio_url, created_at, updated_at FROM employees WHERE id = $1
`

func (q *Queries) GetEmployee(ctx context.Context, id int32) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Role,
		&i.YearsOfExperience,
		pq.Array(&i.Certifications),
		&i.PortfolioUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
