// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: employers.sql

package database

import (
	"context"

	"github.com/lib/pq"
)

const createEmployer = `-- name: CreateEmployer :one
INSERT INTO employers (
    user_id,
    name,
    industry,
    location,
    hiring_modalities
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, industry, location, hiring_modalities, created_at, updated_at
`

type CreateEmployerParams struct {
	UserID           int32
	Name             string
	Industry         string
	Location         string
	HiringModalities []string
}

func (q *Queries) CreateEmployer(ctx context.Context, arg CreateEmployerParams) (Employer, error) {
	row := q.db.QueryRowContext(ctx, createEmployer,
		arg.UserID,
		arg.Name,
		arg.Industry,
		arg.Location,
		pq.Array(arg.HiringModalities),
	)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.Location,
		pq.Array(&i.HiringModalities),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployerByUserID = `-- name: GetEmployerByUserID :one
SELECT id, user_id, name, industry, location, hiring_modalities, created_at, updated_at
FROM employers
WHERE user_id = $1
`

func (q *Queries) GetEmployerByUserID(ctx context.Context, userID int32) (Employer, error) {
	row := q.db.QueryRowContext(ctx, getEmployerByUserID, userID)
	var i Employer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Industry,
		&i.Location,
		pq.Array(&i.HiringModalities),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
