// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_positions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const createJobPosition = `-- name: CreateJobPosition :one
INSERT INTO job_positions (
    employer_id,
    position,
    role,
    required_experience,
    required_education_level,
    available_hours_per_day,
    timezone,
    technical_resources
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, employer_id, position, role, required_experience, required_education_level,
          available_hours_per_day, timezone, technical_resources, created_at, updated_at, deleted_at
`

type CreateJobPositionParams struct {
	EmployerID             int32
	Position               string
	Role                   string
	RequiredExperience     string
	RequiredEducationLevel string
	AvailableHoursPerDay   int16
	Timezone               string
	TechnicalResources     []string
}

func (q *Queries) CreateJobPosition(ctx context.Context, arg CreateJobPositionParams) (JobPosition, error) {
	row := q.db.QueryRowContext(ctx, createJobPosition,
		arg.EmployerID,
		arg.Position,
		arg.Role,
		arg.RequiredExperience,
		arg.RequiredEducationLevel,
		arg.AvailableHoursPerDay,
		arg.Timezone,
		pq.Array(arg.TechnicalResources),
	)
	var i JobPosition
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.Position,
		&i.Role,
		&i.RequiredExperience,
		&i.RequiredEducationLevel,
		&i.AvailableHoursPerDay,
		&i.Timezone,
		pq.Array(&i.TechnicalResources),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveJobPositionByID = `-- name: GetActiveJobPositionByID :one
SELECT id, employer_id, position, role, required_experience, required_education_level,
       available_hours_per_day, timezone, technical_resources, created_at, updated_at, deleted_at
FROM job_positions
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetActiveJobPositionByID(ctx context.Context, id int32) (JobPosition, error) {
	row := q.db.QueryRowContext(ctx, getActiveJobPositionByID, id)
	var i JobPosition
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.Position,
		&i.Role,
		&i.RequiredExperience,
		&i.RequiredEducationLevel,
		&i.AvailableHoursPerDay,
		&i.Timezone,
		pq.Array(&i.TechnicalResources),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveJobPositionsByEmployer = `-- name: ListActiveJobPositionsByEmployer :many
SELECT id, employer_id, position, role, required_experience, required_education_level,
       available_hours_per_day, timezone, technical_resources, created_at, updated_at, deleted_at
FROM job_positions
WHERE employer_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveJobPositionsByEmployer(ctx context.Context, employerID int32) ([]JobPosition, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobPositionsByEmployer, employerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobPosition
	for rows.Next() {
		var i JobPosition
		if err := rows.Scan(
			&i.ID,
			&i.EmployerID,
			&i.Position,
			&i.Role,
			&i.RequiredExperience,
			&i.RequiredEducationLevel,
			&i.AvailableHoursPerDay,
			&i.Timezone,
			pq.Array(&i.TechnicalResources),
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteJobPosition = `-- name: SoftDeleteJobPosition :one
UPDATE job_positions
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, employer_id, deleted_at
`

type SoftDeleteJobPositionRow struct {
	ID         int32
	EmployerID int32
	DeletedAt  sql.NullTime
}

func (q *Queries) SoftDeleteJobPosition(ctx context.Context, id int32) (SoftDeleteJobPositionRow, error) {
	row := q.db.QueryRowContext(ctx, softDeleteJobPosition, id)
	var i SoftDeleteJobPositionRow
	err := row.Scan(&i.ID, &i.EmployerID, &i.DeletedAt)
	return i, err
}

const updateActiveJobPosition = `-- name: UpdateActiveJobPosition :one
UPDATE job_positions
SET position = $2,
    role = $3,
    required_experience = $4,
    required_education_level = $5,
    available_hours_per_day = $6,
    timezone = $7,
    technical_resources = $8,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, employer_id, position, role, required_experience, required_education_level,
          available_hours_per_day, timezone, technical_resources, created_at, updated_at, deleted_at
`

type UpdateActiveJobPositionParams struct {
	ID                     int32
	Position               string
	Role                   string
	RequiredExperience     string
	RequiredEducationLevel string
	AvailableHoursPerDay   int16
	Timezone               string
	TechnicalResources     []string
}

func (q *Queries) UpdateActiveJobPosition(ctx context.Context, arg UpdateActiveJobPositionParams) (JobPosition, error) {
	row := q.db.QueryRowContext(ctx, updateActiveJobPosition,
		arg.ID,
		arg.Position,
		arg.Role,
		arg.RequiredExperience,
		arg.RequiredEducationLevel,
		arg.AvailableHoursPerDay,
		arg.Timezone,
		pq.Array(arg.TechnicalResources),
	)
	var i JobPosition
	err := row.Scan(
		&i.ID,
		&i.EmployerID,
		&i.Position,
		&i.Role,
		&i.RequiredExperience,
		&i.RequiredEducationLevel,
		&i.AvailableHoursPerDay,
		&i.Timezone,
		pq.Array(&i.TechnicalResources),
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
