// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Employee struct {
	ID                int32
	Position          string
	Role              string
	YearsOfExperience string
	Certifications    []string
	PortfolioUrl      sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	UserID            int32
}

type EmployeeEducation struct {
	ID            int32
	EmployeeID    int32
	EducationType string
	Title         string
	Status        string
	Certification sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type EmployeeFile struct {
	ID               int32
	EmployeeID       int32
	Type             string
	Bucket           string
	ObjectKey        string
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	ChecksumSha256   sql.NullString
	Status           string
	CreatedAt        time.Time
	UploadedAt       sql.NullTime
	UpdatedAt        time.Time
}

type EmployeeInternetConnection struct {
	ID         int32
	EmployeeID int32
	Type       string
	Speed      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type EmployeeLocation struct {
	ID         int32
	EmployeeID int32
	Timezone   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type EmployeeProfileAvailability struct {
	ID                   int32
	EmployeeID           int32
	AvailableHoursPerDay sql.NullInt16
	CompatibleProjects   sql.NullInt16
	IncompatibleProjects sql.NullInt16
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type EmployeeProfileTech struct {
	ID           int32
	EmployeeID   int32
	Os           sql.NullString
	PaidSoftware []string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             int32
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
