// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const claimRecommendationBatch = `-- name: ClaimRecommendationBatch :one
UPDATE recommendation_batches
SET status = 'processing',
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'processing')
RETURNING id, subject_type, employee_id, job_position_id, status, created_at, updated_at
`

// Reclamo condicional del trabajo. A diferencia de TransitionRecommendationBatch, que es
// incondicional y le alcanza al productor porque solo cierra un batch que acaba de abrir,
// este no toca un batch terminal: un redelivery de un mensaje cuyo batch ya está
// 'completed' lo devolvería a 'processing' y el reemplazo siguiente destruiría el conjunto
// vigente que ese batch dejó.
//
// El predicado incluye 'processing' y no solo 'pending' a propósito. Excluirlo haría el
// reclamo estrictamente exclusivo, pero convertiría cualquier caída del worker a mitad de
// un batch en un sujeto bloqueado para siempre por el índice único parcial: el redelivery
// no podría reclamarlo. Que dos entregas se solapen es inocuo, porque completar un batch es
// un reemplazo atómico completo y el último en commitear gana.
func (q *Queries) ClaimRecommendationBatch(ctx context.Context, id int32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, claimRecommendationBatch, id)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecommendationBatch = `-- name: CreateRecommendationBatch :one
INSERT INTO recommendation_batches (
    subject_type,
    employee_id,
    job_position_id
)
VALUES ($1, $2, $3)
RETURNING id, subject_type, employee_id, job_position_id, status, created_at, updated_at
`

type CreateRecommendationBatchParams struct {
	SubjectType   string
	EmployeeID    sql.NullInt32
	JobPositionID sql.NullInt32
}

func (q *Queries) CreateRecommendationBatch(ctx context.Context, arg CreateRecommendationBatchParams) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, createRecommendationBatch, arg.SubjectType, arg.EmployeeID, arg.JobPositionID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOtherBatchesForEmployee = `-- name: DeleteOtherBatchesForEmployee :exec
DELETE FROM recommendation_batches
WHERE employee_id = $1
  AND id <> $2
`

type DeleteOtherBatchesForEmployeeParams struct {
	EmployeeID sql.NullInt32
	ID         int32
}

// Poda de retención: al completar un batch se descartan los demás batches del mismo
// sujeto. El ON DELETE CASCADE de recommendations arrastra sus filas.
func (q *Queries) DeleteOtherBatchesForEmployee(ctx context.Context, arg DeleteOtherBatchesForEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherBatchesForEmployee, arg.EmployeeID, arg.ID)
	return err
}

const deleteOtherBatchesForJobPosition = `-- name: DeleteOtherBatchesForJobPosition :exec
DELETE FROM recommendation_batches
WHERE job_position_id = $1
  AND id <> $2
`

type DeleteOtherBatchesForJobPositionParams struct {
	JobPositionID sql.NullInt32
	ID            int32
}

func (q *Queries) DeleteOtherBatchesForJobPosition(ctx context.Context, arg DeleteOtherBatchesForJobPositionParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherBatchesForJobPosition, arg.JobPositionID, arg.ID)
	return err
}

const employeeExists = `-- name: EmployeeExists :one
SELECT EXISTS (SELECT 1 FROM employees WHERE id = $1)
`

// El worker distingue un empleado inexistente de uno sin datos de perfil: el primero cierra
// el batch sin recomendaciones, el segundo es un candidato válido.
func (q *Queries) EmployeeExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, employeeExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getActiveJobPositionRequirements = `-- name: GetActiveJobPositionRequirements :one
SELECT id AS job_position_id,
       required_experience,
       required_education_level,
       available_hours_per_day,
       timezone,
       technical_resources
FROM job_positions
WHERE id = $1
  AND deleted_at IS NULL
`

type GetActiveJobPositionRequirementsRow struct {
	JobPositionID          int32
	RequiredExperience     string
	RequiredEducationLevel string
	AvailableHoursPerDay   int16
	Timezone               string
	TechnicalResources     []string
}

func (q *Queries) GetActiveJobPositionRequirements(ctx context.Context, id int32) (GetActiveJobPositionRequirementsRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveJobPositionRequirements, id)
	var i GetActiveJobPositionRequirementsRow
	err := row.Scan(
		&i.JobPositionID,
		&i.RequiredExperience,
		&i.RequiredEducationLevel,
		&i.AvailableHoursPerDay,
		&i.Timezone,
		pq.Array(&i.TechnicalResources),
	)
	return i, err
}

const getCurrentBatchByEmployee = `-- name: GetCurrentBatchByEmployee :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE employee_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// El batch vigente es el más reciente cualquiera sea su estado: es el que determina si
// el sujeto se muestra procesando, completado, vacío o con error.
func (q *Queries) GetCurrentBatchByEmployee(ctx context.Context, employeeID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getCurrentBatchByEmployee, employeeID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentBatchByJobPosition = `-- name: GetCurrentBatchByJobPosition :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE job_position_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetCurrentBatchByJobPosition(ctx context.Context, jobPositionID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getCurrentBatchByJobPosition, jobPositionID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeScoringProfile = `-- name: GetEmployeeScoringProfile :one

SELECT e.id AS employee_id,
       e.years_of_experience,
       a.available_hours_per_day,
       l.timezone,
       t.paid_software,
       (t.employee_id IS NOT NULL)::boolean AS has_tech_profile,
       ARRAY(
           SELECT ed.education_type
           FROM employee_education ed
           WHERE ed.employee_id = e.id
       )::text[] AS education_types
FROM employees e
LEFT JOIN employee_profile_availability a ON a.employee_id = e.id
LEFT JOIN employee_location l ON l.employee_id = e.id
LEFT JOIN employee_profile_tech t ON t.employee_id = e.id
WHERE e.id = $1
`

type GetEmployeeScoringProfileRow struct {
	EmployeeID           int32
	YearsOfExperience    string
	AvailableHoursPerDay sql.NullInt16
	Timezone             sql.NullString
	PaidSoftware         []string
	HasTechProfile       bool
	EducationTypes       []string
}

// Universo de candidatos. Todas estas consultas alimentan al worker: traducen las filas a
// la entrada normalizada del contrato de scoring. Los puestos eliminados lógicamente quedan
// fuera de todas, porque un puesto eliminado nunca se recomienda ni recibe candidatos.
// Los LEFT JOIN son deliberados: el perfil del empleado se completa en cinco pasos, y un
// paso sin completar debe producir NULL y no la desaparición de la fila. La ausencia de un
// dato y su valor cero son estados distintos que el contrato de scoring distingue.
//
// highest_education se resuelve en Go y no acá: el orden de los niveles ya es parte del
// contrato de scoring, y una segunda copia en un CASE se desincronizaría.
func (q *Queries) GetEmployeeScoringProfile(ctx context.Context, id int32) (GetEmployeeScoringProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeScoringProfile, id)
	var i GetEmployeeScoringProfileRow
	err := row.Scan(
		&i.EmployeeID,
		&i.YearsOfExperience,
		&i.AvailableHoursPerDay,
		&i.Timezone,
		pq.Array(&i.PaidSoftware),
		&i.HasTechProfile,
		pq.Array(&i.EducationTypes),
	)
	return i, err
}

const getLastCompletedBatchByEmployee = `-- name: GetLastCompletedBatchByEmployee :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE employee_id = $1
  AND status = 'completed'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// El conjunto vigente sale del último batch completado, que puede no ser el más
// reciente: un batch fallido posterior no destruye las recomendaciones anteriores.
func (q *Queries) GetLastCompletedBatchByEmployee(ctx context.Context, employeeID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getLastCompletedBatchByEmployee, employeeID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastCompletedBatchByJobPosition = `-- name: GetLastCompletedBatchByJobPosition :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE job_position_id = $1
  AND status = 'completed'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLastCompletedBatchByJobPosition(ctx context.Context, jobPositionID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getLastCompletedBatchByJobPosition, jobPositionID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecommendationBatch = `-- name: GetRecommendationBatch :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE id = $1
`

// El worker necesita distinguir un batch inexistente de uno ya terminal: el primero
// significa que el sujeto o el batch desaparecieron, y el segundo que otro procesamiento
// ya lo cerró. Ambos se reconocen sin trabajo, pero el diagnóstico es distinto.
func (q *Queries) GetRecommendationBatch(ctx context.Context, id int32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getRecommendationBatch, id)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecommendation = `-- name: InsertRecommendation :one
INSERT INTO recommendations (
    batch_id,
    employee_id,
    job_position_id,
    score
)
VALUES ($1, $2, $3, $4)
RETURNING id, batch_id, employee_id, job_position_id, score, created_at
`

type InsertRecommendationParams struct {
	BatchID       int32
	EmployeeID    int32
	JobPositionID int32
	Score         sql.NullString
}

func (q *Queries) InsertRecommendation(ctx context.Context, arg InsertRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, insertRecommendation,
		arg.BatchID,
		arg.EmployeeID,
		arg.JobPositionID,
		arg.Score,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveJobPositionRequirements = `-- name: ListActiveJobPositionRequirements :many
SELECT id AS job_position_id,
       required_experience,
       required_education_level,
       available_hours_per_day,
       timezone,
       technical_resources
FROM job_positions
WHERE deleted_at IS NULL
ORDER BY id
`

type ListActiveJobPositionRequirementsRow struct {
	JobPositionID          int32
	RequiredExperience     string
	RequiredEducationLevel string
	AvailableHoursPerDay   int16
	Timezone               string
	TechnicalResources     []string
}

func (q *Queries) ListActiveJobPositionRequirements(ctx context.Context) ([]ListActiveJobPositionRequirementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobPositionRequirements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveJobPositionRequirementsRow
	for rows.Next() {
		var i ListActiveJobPositionRequirementsRow
		if err := rows.Scan(
			&i.JobPositionID,
			&i.RequiredExperience,
			&i.RequiredEducationLevel,
			&i.AvailableHoursPerDay,
			&i.Timezone,
			pq.Array(&i.TechnicalResources),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeRecommendationsForJobPosition = `-- name: ListEmployeeRecommendationsForJobPosition :many
SELECT r.id, r.batch_id, r.score,
       e.id AS employee_id,
       e.user_id,
       e.position,
       e.role,
       e.years_of_experience,
       e.certifications,
       e.portfolio_url,
       e.created_at,
       e.updated_at
FROM recommendations r
JOIN employees e ON e.id = r.employee_id
JOIN job_positions j ON j.id = r.job_position_id
WHERE r.batch_id = $1
  AND j.deleted_at IS NULL
ORDER BY r.score DESC NULLS LAST, e.updated_at DESC, r.id ASC
LIMIT $2 OFFSET $3
`

type ListEmployeeRecommendationsForJobPositionParams struct {
	BatchID int32
	Limit   int32
	Offset  int32
}

type ListEmployeeRecommendationsForJobPositionRow struct {
	ID                int32
	BatchID           int32
	Score             sql.NullString
	EmployeeID        int32
	UserID            int32
	Position          string
	Role              string
	YearsOfExperience string
	Certifications    []string
	PortfolioUrl      sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListEmployeeRecommendationsForJobPosition(ctx context.Context, arg ListEmployeeRecommendationsForJobPositionParams) ([]ListEmployeeRecommendationsForJobPositionRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeRecommendationsForJobPosition, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeRecommendationsForJobPositionRow
	for rows.Next() {
		var i ListEmployeeRecommendationsForJobPositionRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Score,
			&i.EmployeeID,
			&i.UserID,
			&i.Position,
			&i.Role,
			&i.YearsOfExperience,
			pq.Array(&i.Certifications),
			&i.PortfolioUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeScoringProfiles = `-- name: ListEmployeeScoringProfiles :many
SELECT e.id AS employee_id,
       e.years_of_experience,
       a.available_hours_per_day,
       l.timezone,
       t.paid_software,
       (t.employee_id IS NOT NULL)::boolean AS has_tech_profile,
       ARRAY(
           SELECT ed.education_type
           FROM employee_education ed
           WHERE ed.employee_id = e.id
       )::text[] AS education_types
FROM employees e
LEFT JOIN employee_profile_availability a ON a.employee_id = e.id
LEFT JOIN employee_location l ON l.employee_id = e.id
LEFT JOIN employee_profile_tech t ON t.employee_id = e.id
ORDER BY e.id
`

type ListEmployeeScoringProfilesRow struct {
	EmployeeID           int32
	YearsOfExperience    string
	AvailableHoursPerDay sql.NullInt16
	Timezone             sql.NullString
	PaidSoftware         []string
	HasTechProfile       bool
	EducationTypes       []string
}

func (q *Queries) ListEmployeeScoringProfiles(ctx context.Context) ([]ListEmployeeScoringProfilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeScoringProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeScoringProfilesRow
	for rows.Next() {
		var i ListEmployeeScoringProfilesRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.YearsOfExperience,
			&i.AvailableHoursPerDay,
			&i.Timezone,
			pq.Array(&i.PaidSoftware),
			&i.HasTechProfile,
			pq.Array(&i.EducationTypes),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRecommendationsForEmployee = `-- name: ListJobRecommendationsForEmployee :many
SELECT r.id, r.batch_id, r.score,
       j.id AS job_position_id,
       j.employer_id,
       j.position,
       j.role,
       j.required_experience,
       j.required_education_level,
       j.available_hours_per_day,
       j.timezone,
       j.technical_resources,
       j.created_at,
       j.updated_at
FROM recommendations r
JOIN job_positions j ON j.id = r.job_position_id
WHERE r.batch_id = $1
  AND j.deleted_at IS NULL
ORDER BY r.score DESC NULLS LAST, j.created_at DESC, r.id ASC
LIMIT $2 OFFSET $3
`

type ListJobRecommendationsForEmployeeParams struct {
	BatchID int32
	Limit   int32
	Offset  int32
}

type ListJobRecommendationsForEmployeeRow struct {
	ID                     int32
	BatchID                int32
	Score                  sql.NullString
	JobPositionID          int32
	EmployerID             int32
	Position               string
	Role                   string
	RequiredExperience     string
	RequiredEducationLevel string
	AvailableHoursPerDay   int16
	Timezone               string
	TechnicalResources     []string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

// Los puestos eliminados lógicamente quedan fuera con independencia de que la
// recomendación se haya generado antes de esa eliminación.
func (q *Queries) ListJobRecommendationsForEmployee(ctx context.Context, arg ListJobRecommendationsForEmployeeParams) ([]ListJobRecommendationsForEmployeeRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobRecommendationsForEmployee, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobRecommendationsForEmployeeRow
	for rows.Next() {
		var i ListJobRecommendationsForEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Score,
			&i.JobPositionID,
			&i.EmployerID,
			&i.Position,
			&i.Role,
			&i.RequiredExperience,
			&i.RequiredEducationLevel,
			&i.AvailableHoursPerDay,
			&i.Timezone,
			pq.Array(&i.TechnicalResources),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionRecommendationBatch = `-- name: TransitionRecommendationBatch :one
UPDATE recommendation_batches
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, subject_type, employee_id, job_position_id, status, created_at, updated_at
`

type TransitionRecommendationBatchParams struct {
	ID     int32
	Status string
}

func (q *Queries) TransitionRecommendationBatch(ctx context.Context, arg TransitionRecommendationBatchParams) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, transitionRecommendationBatch, arg.ID, arg.Status)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
