// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recommendations.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const createRecommendationBatch = `-- name: CreateRecommendationBatch :one
INSERT INTO recommendation_batches (
    subject_type,
    employee_id,
    job_position_id
)
VALUES ($1, $2, $3)
RETURNING id, subject_type, employee_id, job_position_id, status, created_at, updated_at
`

type CreateRecommendationBatchParams struct {
	SubjectType   string
	EmployeeID    sql.NullInt32
	JobPositionID sql.NullInt32
}

func (q *Queries) CreateRecommendationBatch(ctx context.Context, arg CreateRecommendationBatchParams) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, createRecommendationBatch, arg.SubjectType, arg.EmployeeID, arg.JobPositionID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOtherBatchesForEmployee = `-- name: DeleteOtherBatchesForEmployee :exec
DELETE FROM recommendation_batches
WHERE employee_id = $1
  AND id <> $2
`

type DeleteOtherBatchesForEmployeeParams struct {
	EmployeeID sql.NullInt32
	ID         int32
}

// Poda de retención: al completar un batch se descartan los demás batches del mismo
// sujeto. El ON DELETE CASCADE de recommendations arrastra sus filas.
func (q *Queries) DeleteOtherBatchesForEmployee(ctx context.Context, arg DeleteOtherBatchesForEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherBatchesForEmployee, arg.EmployeeID, arg.ID)
	return err
}

const deleteOtherBatchesForJobPosition = `-- name: DeleteOtherBatchesForJobPosition :exec
DELETE FROM recommendation_batches
WHERE job_position_id = $1
  AND id <> $2
`

type DeleteOtherBatchesForJobPositionParams struct {
	JobPositionID sql.NullInt32
	ID            int32
}

func (q *Queries) DeleteOtherBatchesForJobPosition(ctx context.Context, arg DeleteOtherBatchesForJobPositionParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherBatchesForJobPosition, arg.JobPositionID, arg.ID)
	return err
}

const getCurrentBatchByEmployee = `-- name: GetCurrentBatchByEmployee :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE employee_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// El batch vigente es el más reciente cualquiera sea su estado: es el que determina si
// el sujeto se muestra procesando, completado, vacío o con error.
func (q *Queries) GetCurrentBatchByEmployee(ctx context.Context, employeeID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getCurrentBatchByEmployee, employeeID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrentBatchByJobPosition = `-- name: GetCurrentBatchByJobPosition :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE job_position_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetCurrentBatchByJobPosition(ctx context.Context, jobPositionID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getCurrentBatchByJobPosition, jobPositionID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastCompletedBatchByEmployee = `-- name: GetLastCompletedBatchByEmployee :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE employee_id = $1
  AND status = 'completed'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// El conjunto vigente sale del último batch completado, que puede no ser el más
// reciente: un batch fallido posterior no destruye las recomendaciones anteriores.
func (q *Queries) GetLastCompletedBatchByEmployee(ctx context.Context, employeeID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getLastCompletedBatchByEmployee, employeeID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastCompletedBatchByJobPosition = `-- name: GetLastCompletedBatchByJobPosition :one
SELECT id, subject_type, employee_id, job_position_id, status, created_at, updated_at
FROM recommendation_batches
WHERE job_position_id = $1
  AND status = 'completed'
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLastCompletedBatchByJobPosition(ctx context.Context, jobPositionID sql.NullInt32) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, getLastCompletedBatchByJobPosition, jobPositionID)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecommendation = `-- name: InsertRecommendation :one
INSERT INTO recommendations (
    batch_id,
    employee_id,
    job_position_id,
    score
)
VALUES ($1, $2, $3, $4)
RETURNING id, batch_id, employee_id, job_position_id, score, created_at
`

type InsertRecommendationParams struct {
	BatchID       int32
	EmployeeID    int32
	JobPositionID int32
	Score         sql.NullString
}

func (q *Queries) InsertRecommendation(ctx context.Context, arg InsertRecommendationParams) (Recommendation, error) {
	row := q.db.QueryRowContext(ctx, insertRecommendation,
		arg.BatchID,
		arg.EmployeeID,
		arg.JobPositionID,
		arg.Score,
	)
	var i Recommendation
	err := row.Scan(
		&i.ID,
		&i.BatchID,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Score,
		&i.CreatedAt,
	)
	return i, err
}

const listEmployeeRecommendationsForJobPosition = `-- name: ListEmployeeRecommendationsForJobPosition :many
SELECT r.id, r.batch_id, r.score,
       e.id AS employee_id,
       e.user_id,
       e.position,
       e.role,
       e.years_of_experience,
       e.certifications,
       e.portfolio_url,
       e.created_at,
       e.updated_at
FROM recommendations r
JOIN employees e ON e.id = r.employee_id
JOIN job_positions j ON j.id = r.job_position_id
WHERE r.batch_id = $1
  AND j.deleted_at IS NULL
ORDER BY r.score DESC NULLS LAST, e.updated_at DESC, r.id ASC
LIMIT $2 OFFSET $3
`

type ListEmployeeRecommendationsForJobPositionParams struct {
	BatchID int32
	Limit   int32
	Offset  int32
}

type ListEmployeeRecommendationsForJobPositionRow struct {
	ID                int32
	BatchID           int32
	Score             sql.NullString
	EmployeeID        int32
	UserID            int32
	Position          string
	Role              string
	YearsOfExperience string
	Certifications    []string
	PortfolioUrl      sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListEmployeeRecommendationsForJobPosition(ctx context.Context, arg ListEmployeeRecommendationsForJobPositionParams) ([]ListEmployeeRecommendationsForJobPositionRow, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeRecommendationsForJobPosition, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEmployeeRecommendationsForJobPositionRow
	for rows.Next() {
		var i ListEmployeeRecommendationsForJobPositionRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Score,
			&i.EmployeeID,
			&i.UserID,
			&i.Position,
			&i.Role,
			&i.YearsOfExperience,
			pq.Array(&i.Certifications),
			&i.PortfolioUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobRecommendationsForEmployee = `-- name: ListJobRecommendationsForEmployee :many
SELECT r.id, r.batch_id, r.score,
       j.id AS job_position_id,
       j.employer_id,
       j.position,
       j.role,
       j.required_experience,
       j.required_education_level,
       j.available_hours_per_day,
       j.timezone,
       j.technical_resources,
       j.created_at,
       j.updated_at
FROM recommendations r
JOIN job_positions j ON j.id = r.job_position_id
WHERE r.batch_id = $1
  AND j.deleted_at IS NULL
ORDER BY r.score DESC NULLS LAST, j.created_at DESC, r.id ASC
LIMIT $2 OFFSET $3
`

type ListJobRecommendationsForEmployeeParams struct {
	BatchID int32
	Limit   int32
	Offset  int32
}

type ListJobRecommendationsForEmployeeRow struct {
	ID                     int32
	BatchID                int32
	Score                  sql.NullString
	JobPositionID          int32
	EmployerID             int32
	Position               string
	Role                   string
	RequiredExperience     string
	RequiredEducationLevel string
	AvailableHoursPerDay   int16
	Timezone               string
	TechnicalResources     []string
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

// Los puestos eliminados lógicamente quedan fuera con independencia de que la
// recomendación se haya generado antes de esa eliminación.
func (q *Queries) ListJobRecommendationsForEmployee(ctx context.Context, arg ListJobRecommendationsForEmployeeParams) ([]ListJobRecommendationsForEmployeeRow, error) {
	rows, err := q.db.QueryContext(ctx, listJobRecommendationsForEmployee, arg.BatchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobRecommendationsForEmployeeRow
	for rows.Next() {
		var i ListJobRecommendationsForEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.Score,
			&i.JobPositionID,
			&i.EmployerID,
			&i.Position,
			&i.Role,
			&i.RequiredExperience,
			&i.RequiredEducationLevel,
			&i.AvailableHoursPerDay,
			&i.Timezone,
			pq.Array(&i.TechnicalResources),
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionRecommendationBatch = `-- name: TransitionRecommendationBatch :one
UPDATE recommendation_batches
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, subject_type, employee_id, job_position_id, status, created_at, updated_at
`

type TransitionRecommendationBatchParams struct {
	ID     int32
	Status string
}

func (q *Queries) TransitionRecommendationBatch(ctx context.Context, arg TransitionRecommendationBatchParams) (RecommendationBatch, error) {
	row := q.db.QueryRowContext(ctx, transitionRecommendationBatch, arg.ID, arg.Status)
	var i RecommendationBatch
	err := row.Scan(
		&i.ID,
		&i.SubjectType,
		&i.EmployeeID,
		&i.JobPositionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
